name=MiniCtrlBoxLib
version=5.0.8
author=Christoph Kilgenstein <christoph@kilgenstein.eu>
maintainer=Christoph Kilgenstein <christoph@kilgenstein.eu>
sentence=High-level hardware abstraction library for the MiniCtrlBox (OLED, EEPROM, MCP23017, Buttons, CAN, etc.)
paragraph=This library provides a high-level interface to the various hardware components of the MiniCtrlBox 
paragraph=It is used fpr a school project and is not intended for production use. It is provided as-is without any warranty.
category=Signal Input/Output
url=https://github.com/chriskilgi/MiniCtrlBoxLib
architectures=*
includes=MiniCtrlBox.h


